# Generated by Django 3.0.7 on 2020-06-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
