# Generated by Django 3.0.7 on 2020-06-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_manufacturer_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoecolor',
            name='color_name',
            field=models.CharField(choices=[('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Blue', 'Blue'), ('Indigo', 'Indigo'), ('Violet', 'Violet'), ('White', 'White'), ('Black', 'Black')], default='Black', max_length=6),
        ),
        migrations.AlterField(
            model_name='shoetype',
            name='style',
            field=models.CharField(choices=[('Sneaker', 'Sneaker'), ('Boot', 'Boot'), ('Sandal', 'Sandal'), ('Dress', 'Dress'), ('Other', 'Other')], default='Sneaker', max_length=7),
        ),
    ]
